name: cnip-cidr-gen

on:
  schedule:
    - cron: '5 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/routeros-cnip-cidr

      - name: Update cn_ip_cidr.rsc
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |-
          bash $GITHUB_WORKSPACE/routeros-cnip-cidr/generator.bash

      - name: Commit and push if changed
        run: |-
          cd $GITHUB_WORKSPACE/routeros-cnip-cidr/
          git diff
          git config --global user.email "action_bot@rookiezoe.com"
          git config --global user.name "ActionBot"
          git add -A
          git commit -m "Update 'cn_ip_cidr.rsc'" || exit 0
          git push 
